// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Movie controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, PagedListOfMovieDto } from "../models";

@Injectable({ providedIn: "root" })
export class MovieService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getMovies(pageNumber?: number | string, pageSize?: number | string, titleSearchTerm?: string, genres?: Array<string>, language?: string, sortColumn?: string, sortDirection?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PagedListOfMovieDto>;
    getMovies(pageNumber?: number | string, pageSize?: number | string, titleSearchTerm?: string, genres?: Array<string>, language?: string, sortColumn?: string, sortDirection?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PagedListOfMovieDto>>;
    getMovies(pageNumber?: number | string, pageSize?: number | string, titleSearchTerm?: string, genres?: Array<string>, language?: string, sortColumn?: string, sortDirection?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PagedListOfMovieDto>>;
    getMovies(pageNumber?: number | string, pageSize?: number | string, titleSearchTerm?: string, genres?: Array<string>, language?: string, sortColumn?: string, sortDirection?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/Movie`;

        let params = new HttpParams();
        if (pageNumber != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageNumber, 'PageNumber');
        }
        if (pageSize != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageSize, 'PageSize');
        }
        if (titleSearchTerm != null) {
            params = HttpParamsBuilder.addToHttpParams(params, titleSearchTerm, 'TitleSearchTerm');
        }
        if (genres != null) {
            params = HttpParamsBuilder.addToHttpParams(params, genres, 'Genres');
        }
        if (language != null) {
            params = HttpParamsBuilder.addToHttpParams(params, language, 'Language');
        }
        if (sortColumn != null) {
            params = HttpParamsBuilder.addToHttpParams(params, sortColumn, 'SortColumn');
        }
        if (sortDirection != null) {
            params = HttpParamsBuilder.addToHttpParams(params, sortDirection, 'SortDirection');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json, text/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
