// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface MovieDto {
    id: string;
    releaseDate: Date;
    title: string;
    overview: string;
    popularity: number | string;
    voteCount: number | string;
    voteAverage: number | string;
    originalLanguage: string;
    genre: Array<string>;
    posterUrl: string;
}

export interface PagedListOfMovieDto {
    items: Array<MovieDto>;
    totalCount: number | string;
    pageNumber: number | string;
    pageSize: number | string;
    totalPages?: number | string;
    hasPrevious?: boolean;
    hasNext?: boolean;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
